---
title: "MRA - Assignment 2"
format: pdf
editor: visual
---

## Q3. Model Selection

```{r}
library(tidyverse)
library(dplyr)
library(olsrr)
```

```{r}
crime_data = read_csv("Crimes.csv")
crime_data
```

#### a)

```{r}
crime_model = lm(VR ~ ., data = crime_data)
tab = ols_step_all_possible(crime_model)
results = tab$result[,c("predictors","aic","sbc","rsquare")]
results
```

#### b)

```{r}
print(c(results$predictors[which.min(results$aic)],results$aic[which.min(results$aic)]))
print(c(results$predictors[which.min(results$sbc)],results$sbc[which.min(results$sbc)]))
print(c(results$predictors[which.max(results$rsquare)],results$rsquare[which.max(results$rsquare)]))
```

#### c)

```{r}
combinations = list(("1"),c("P","M","MR"),c("M + P","MR + P","MR + M"),c("MR + M + P"))
min = 100000000
min_combination = ""

for(i in 1:length(combinations)){
  flag = FALSE
  for(j in 1:length(combinations[[i]])){
    f = as.formula(paste("VR ~ ",paste(combinations[[i]][j])))
    crime_model = lm(f,data = crime_data)
    lm = sum(log(dnorm(crime_data$VR,fitted.values(crime_model),
                       sd = summary(crime_model)$sigma)))
    bic = -2 * lm + (i+1) * log(nrow(crime_data))
    if(bic < min){
      min = bic
      min_combination = combinations[[i]][j]
      flag = TRUE
    }
  }
  if(flag == FALSE){
    break
  }
}

print(min)
print(min_combination)
```

#### d)

By looking at the BIC values, the best possible subset found using the all possible regressions was MR + M with a BIC value of 679.282922. The forward selection algorithm using the BIC found the same subset MR + M with a BIC value of 679.3748.

**...write more**

#### e)

**...write**

## Q2)

```{r}
football = read_csv("football.csv")
football
```

#### a)

```{r}
football_model = lm(y ~ x2 + x7 + x8,data=football)
summary(football_model)
```

#### b) ...write stuff

```{r}
y_bar = mean(football$y)

sst = sum((football$y - y_bar)^2)
sse = sum((football$y - fitted.values(football_model))^2)
ssr = sum((fitted.values(football_model) - y_bar)^2)

cat("sse = ",sse," , ","ssr = ",ssr," , ","sst = ",sst)
```

The relationship between SSt, SSe, and SSr:

SSt = SSe + SSr.

```{r}
sse + ssr
```

```{r}
p = 3
n = nrow(football)
df_sse = n - p - 1
df_ssr = p
df_sst = df_sse + df_ssr
X = model.matrix(football_model)

cat("DF of sse = ",df_sse," , ","DF of ssr = ",df_ssr," , ","DF of sst = ",df_sst)
```

```{r}
mst = sst / df_sst
mse = sse / df_sse
msr = ssr / df_ssr
cat("MSE = ",mse," , ","MSR = ",msr," , ","MST = ",mst)
```

#### c) write and do stuff....

```{r}
beta = solve(t(X)%*%X)%*%t(X)%*%football$y
sigma_2 = sse / (n - p - 1)
sigma = sigma_2 * solve(t(X)%*%X)
sigma

t_b1 = beta[2,1] / sqrt(sigma[2,2])
t_b2 = beta[3,1] / sqrt(sigma[11])
t_b3 = beta[4,1] / sqrt(sigma[16])

print(c("T_" = t_b1, "T_" = t_b2, "T_" = t_b3))
```

#### d)

```{r}
r2 = 1 - (sse/sst)
r2_adj = 1 - (mse/mst)

print(c(r2 = r2,r2_adj = r2_adj))
```

#### e)

```{r}
f_stat = msr/mse
c(f_stat = f_stat,"95% CI F distribution" = qf(0.95,p,n-p-1))

```

Reject H0

#### f)

```{r}

```

#### g)

```{r}
X_Star = matrix(c(1,2300,56,2100),ncol=1)
X_Star

Y_Star_mean = t(X_Star)%*%matrix(beta,ncol=1)
Y_Star_mean_upper = Y_Star_mean + qt(0.05,n-p-1) * sqrt(sigma_2 * t(X_Star)%*%solve(t(X)%*%(X))%*%X_Star)
```
